package("ofxcv")
    set_homepage("https://github.com/kylemcdonald/ofxCv")
    set_description("Alternative approach to interfacing with OpenCv from openFrameworks")

    set_urls("https://github.com/kylemcdonald/ofxCv.git")
    add_versions("2024.05.25", "209a3986a8f8e1928c7a11f6e1c5d8ea5406e639")

    add_deps("openframeworks", "opencv")
    -- add_includedirs("include")
    on_install(function (package) 
        io.writefile("xmake.lua", [[
            add_rules("mode.debug", "mode.release")
            add_requires("openframeworks")
            add_requires("opencv")
            set_languages("cxx17")
            target("ofxcv")
                set_kind("$(kind)")
                add_files("libs/**.cpp")
                add_headerfiles("libs/**.h")
                add_headerfiles("src/*.h")
                add_includedirs("src")
                add_includedirs("libs/CLD/include/CLD", "libs/CLD/include")
                add_includedirs("libs/ofxCv/include/ofxCv", "libs/ofxCv/include")
                add_packages("openframeworks", "opencv")
        ]])
        os.cp("libs/ofxCv/include/ofxCv", path.join(package:installdir("include"), "ofxCv"))
        import("package.tools.xmake").install(package)
    end)